apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
spec:
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: sonar3:31111/helloworld-sivanov:rc
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-secret


