apiVersion: v1
kind: Namespace
metadata:
  name: vtarasevich
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuZXh1cy1kb2NrLms4cy5wbGF5cGl0LmJ5OjgwIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6ImFkbWluIiwiYXV0aCI6IllXUnRhVzQ2WVdSdGFXND0ifX19
kind: Secret
metadata:
  name: docker-secret
  namespace: vtarasevich
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: vtarasevich
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 25%
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: IMAGE
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /helloworld-ws
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tocmat-service
  namespace: vtarasevich
  labels:
    app: tomcat
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tomcat
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat-ingress
  namespace: vtarasevich
  annotations:
    nginx.org/rewrites: serviceName=tocmat-service rewrite=/helloworld-ws/
spec:
  rules:
  - host: vtarasevich-app.k8s.playpit.by
    http:
      paths:
      - path: /
        backend:
          serviceName: tocmat-service
          servicePort: 8080
