apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: sonar
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: postgresql-storage
  resources:
    requests:
      storage: 2Gi
