
kubectl create secret generic postgres-pwd --namespace=sonar --from-literal=password-post=123456
kubectl create ns sonar


cat <<EOF > install_sonar.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresdb
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /db/postgresql/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: sonar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-postgres
  namespace: sonar
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: sonar-postgres
      labels:
        name: sonar-postgres
        app: postgres
    spec:
      containers:
        - image: postgres:latest
          name: sonar-postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password-post
            - name: POSTGRES_USER
              value: sonar
          ports:
            - containerPort: 5432
              name: postgresport
          volumeMounts:
            - name: postgresvolume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresvolume
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar-postgres
  name: sonar-postgres
  namespace: sonar
spec:
  ports:
    - port: 5432
      name: posgres-svc-port
  selector:
    name: sonar-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  labels:
    app: sonarqube
  namespace: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      name: sonarqube
      labels:
        name: sonarqube
        app: sonarqube
      namespace: sonar
    spec:
      containers:
        - image: sonarqube:7.1
          args:
            - -Dsonar.web.context=/sonar
          name: sonarqube
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password-post
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonar-postgres:5432/sonar
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sonar
  name: sonar-svc
  namespace: sonar
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9000
      name: sonarport
  selector:
    name: sonarqube
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonar-ingress
  namespace: sonar
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sonar
    http:
      paths: 
      - path: /
        backend:
          serviceName: sonar-svc
          servicePort: sonar-svc
EOF



