apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data
  namespace: nexus-ns
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-jenkins
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/nexus_data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-claim
  namespace: nexus-ns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 3Gi