---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  type: ClusterIP
  # type: LoadBalancer
  # loadBalancerIP: 192.168.56.254
  ports:
  - name: nexus-svc
    protocol: TCP
    port: 8081
    targetPort: nexus-port
  - name: nexus-docker
    protocol: TCP
    port: 20000
    targetPort: docker-port