- name: Check that jenkins.war is not exists
  stat:
    path: "{{ JENKINS_HOME }}/jenkins.war"
  become: yes
  become_user: "{{ jenkins_user }}"
  register: jenkins_war

- name: Download jenkins.war
  get_url:
    url: "{{ jenkins_url }}"
    dest: "{{ JENKINS_HOME }}"
  become: yes
  become_user: "{{ jenkins_user }}"
  when: jenkins_war.stat.exists == False
