apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-docker
  template:
    metadata:
      labels:
        app: tomcat-docker
    spec:
      containers:
        - name: tomcat
          image: 192.168.56.106:30082/anikitsenka/tomcat:latest
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /helloworld-ws
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: tomcat-docker-svc
spec:
  type: NodePort
  ports:
    - name: tomcat
      port: 8080
      nodePort: 30080
      targetPort: 8080
  selector:
    app: tomcat-docker
