- name: Deploying Persistent Volume (Claim) for Jenkins
  shell: |
    kubectl apply -f "{{ item }}"
  with_items:
  - "{{ WORK_FOLDER }}/persistent_volume.yml"
  - "{{ WORK_FOLDER }}/persistent_volume_claim.yml"

- name: Deploying jenkins
  shell: |
    kubectl apply -f "{{ item }}"
  with_items:
  - "{{ WORK_FOLDER }}/deployment.yml"
  - "{{ WORK_FOLDER }}/service.yml"

- name: Create Ingress
  shell: |
    kubectl apply -f "{{ WORK_FOLDER }}/ingress.yml"

- name: Create Service Account for Jenkins
  shell: |
    kubectl create clusterrolebinding jenkins --clusterrole cluster-admin --serviceaccount=jenkins:default
