- name: Add vagrant to group 'docker'
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes

- name: Create directory for docker configuration
  file:
    path: /etc/docker
    state: directory
  become: yes
                                                                               
- name: Configuring Docker Daemon
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  become: yes
  notify:
  - Restart Docker
